import { Bookmark, FileText, Filter, LockKeyhole, Search, ShieldAlert, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const typeLabels: Record<string, string> = { cours: "Cours", td: "TD", tp: "TP", examen: "Examen", corrige: "Corrigé", fiche: "Fiche de révision", rapport: "Rapport de stage", officiel: "Document officiel", autre: "Autre" };

export default function Library() {
  const { isAuthenticated, loading } = useAuth();
  const [, navigate] = useLocation();
  const catalog = trpc.catalog.get.useQuery();
  const [search, setSearch] = useState("");
  const [programId, setProgramId] = useState<number | undefined>();
  const [levelId, setLevelId] = useState<number | undefined>();
  const [academicYearId, setAcademicYearId] = useState<number | undefined>();
  const [courseId, setCourseId] = useState<number | undefined>();
  const [resourceType, setResourceType] = useState<string | undefined>();
  const [showFilters, setShowFilters] = useState(false);
  const filters = useMemo(() => ({ search: search || undefined, programId, levelId, academicYearId, courseId, resourceType }), [search, programId, levelId, academicYearId, courseId, resourceType]);
  const resources = trpc.resources.list.useQuery(filters, { enabled: isAuthenticated });
  const favorite = trpc.resources.favorite.useMutation({ onSuccess: () => toast.success("Favoris mis à jour") });
  const report = trpc.resources.report.useMutation({ onSuccess: () => toast.success("Merci, le signalement a été transmis") });

  if (loading) return <AppShell><div className="container py-24 text-center text-[#6c8177]">Chargement de votre espace…</div></AppShell>;
  if (!isAuthenticated) return <AppShell><div className="container py-24"><div className="mx-auto max-w-lg rounded-[2rem] border border-[#dce8df] bg-white p-8 text-center shadow-xl shadow-[#18332e]/5"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e0f0e5] text-[#0f4c45]"><LockKeyhole size={25} /></div><h1 className="mt-5 font-display text-3xl font-bold text-[#0f4c45]">Bibliothèque réservée</h1><p className="mt-3 text-sm leading-6 text-[#6c8177]">Connectez-vous pour consulter les ressources validées de l'ESTBA et contribuer à la mémoire académique.</p><Button onClick={startLogin} className="mt-6 rounded-full bg-[#0f4c45] text-white hover:bg-[#0a3b36]">Se connecter</Button></div></div></AppShell>;

  const clearFilters = () => { setProgramId(undefined); setLevelId(undefined); setAcademicYearId(undefined); setCourseId(undefined); setResourceType(undefined); setSearch(""); };
  const activeFilterCount = [programId, levelId, academicYearId, courseId, resourceType].filter(Boolean).length;

  return <AppShell>
    <section className="border-b border-[#dce8df] bg-[#e8f1e7]"><div className="container py-12"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#c87536]"><LibraryIcon />Catalogue vivant</div><h1 className="mt-2 font-display text-4xl font-bold tracking-tight text-[#0f4c45]">La bibliothèque de l'ESTBA</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#5f766b]">Explorez les documents transmis par les étudiants et validés par l'administration.</p></div><Button onClick={() => navigate("/contribuer")} className="rounded-full bg-[#0f4c45] text-white hover:bg-[#0a3b36]"><Sparkles size={16} />Contribuer</Button></div><div className="relative mt-8 max-w-3xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#7b9288]" size={19} /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher un cours, une UE, un examen…" className="h-14 rounded-2xl border-white bg-white pl-12 pr-4 text-base shadow-lg shadow-[#18332e]/5 focus-visible:ring-[#8ab694]" /></div></div></section>

    <section className="container py-8"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Button variant="outline" onClick={() => setShowFilters(!showFilters)} className={`rounded-full border-[#cfe0d5] bg-white text-[#0f4c45] ${showFilters ? "bg-[#e0f0e5]" : ""}`}><SlidersHorizontal size={16} />Filtres {activeFilterCount > 0 && <span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#0f4c45] text-[10px] text-white">{activeFilterCount}</span>}</Button>{(activeFilterCount > 0 || search) && <Button variant="ghost" onClick={clearFilters} className="rounded-full text-[#7b9288] hover:text-[#0f4c45]"><X size={15} />Réinitialiser</Button>}</div><div className="text-sm text-[#7b9288]">{resources.isLoading ? "Recherche…" : `${resources.data?.length ?? 0} ressource${resources.data?.length === 1 ? "" : "s"}`}</div></div>
      {showFilters && <div className="mt-5 grid gap-3 rounded-2xl border border-[#dce8df] bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-bold text-[#5d746a]">Filière<select value={programId ?? ""} onChange={e => setProgramId(e.target.value ? Number(e.target.value) : undefined)} className="mt-2 h-10 w-full rounded-xl border border-[#dce8df] bg-white px-3 text-sm text-[#18332e]"><option value="">Toutes</option>{catalog.data?.programs.map(program => <option key={program.id} value={program.id}>{program.code}</option>)}</select></label><label className="text-xs font-bold text-[#5d746a]">Niveau<select value={levelId ?? ""} onChange={e => setLevelId(e.target.value ? Number(e.target.value) : undefined)} className="mt-2 h-10 w-full rounded-xl border border-[#dce8df] bg-white px-3 text-sm text-[#18332e]"><option value="">Tous</option>{catalog.data?.levels.map(level => <option key={level.id} value={level.id}>{level.label}</option>)}</select></label><label className="text-xs font-bold text-[#5d746a]">Année<select value={academicYearId ?? ""} onChange={e => setAcademicYearId(e.target.value ? Number(e.target.value) : undefined)} className="mt-2 h-10 w-full rounded-xl border border-[#dce8df] bg-white px-3 text-sm text-[#18332e]"><option value="">Toutes</option>{catalog.data?.academicYears.map(year => <option key={year.id} value={year.id}>{year.label}</option>)}</select></label><label className="text-xs font-bold text-[#5d746a]">UE<select value={courseId ?? ""} onChange={e => setCourseId(e.target.value ? Number(e.target.value) : undefined)} className="mt-2 h-10 w-full rounded-xl border border-[#dce8df] bg-white px-3 text-sm text-[#18332e]"><option value="">Toutes</option>{catalog.data?.courses.map(course => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><label className="text-xs font-bold text-[#5d746a]">Type<select value={resourceType ?? ""} onChange={e => setResourceType(e.target.value || undefined)} className="mt-2 h-10 w-full rounded-xl border border-[#dce8df] bg-white px-3 text-sm text-[#18332e]"><option value="">Tous</option>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>}

      <div className="mt-7 grid gap-4 lg:grid-cols-2">{resources.isLoading ? [1, 2, 3, 4].map(i => <div key={i} className="h-44 animate-pulse rounded-2xl bg-[#e8eee8]" />) : resources.data?.map(resource => <article key={resource.id} className="group rounded-2xl border border-[#dce8df] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#b5d0bb] hover:shadow-lg hover:shadow-[#18332e]/5"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#e0f0e5] text-[#0f4c45]"><FileText size={20} /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge className="border-0 bg-[#f8e6c8] text-[#8b5319]">{typeLabels[resource.resourceType] ?? resource.resourceType}</Badge><span className="text-[11px] font-semibold text-[#9aada3]">V.{resource.versionNumber}</span></div><h2 className="mt-2 truncate font-display text-lg font-bold text-[#18332e]">{resource.title}</h2></div></div><Button aria-label="Ajouter aux favoris" variant="ghost" size="icon" className="shrink-0 rounded-full text-[#8aa197] hover:bg-[#edf5ee] hover:text-[#c87536]" onClick={() => favorite.mutate({ resourceId: resource.id })}><Bookmark size={18} /></Button></div><p className="mt-3 line-clamp-2 text-sm leading-5 text-[#6c8177]">{resource.description || "Aucune description ajoutée."}</p><div className="mt-4 flex flex-wrap gap-2 text-[11px] font-semibold text-[#6c8177]"><span className="rounded-md bg-[#f3f6f2] px-2 py-1">{resource.programCode}</span><span className="rounded-md bg-[#f3f6f2] px-2 py-1">{resource.levelLabel}</span><span className="rounded-md bg-[#f3f6f2] px-2 py-1">{resource.academicYearLabel}</span><span className="rounded-md bg-[#f3f6f2] px-2 py-1">{resource.courseName}</span></div><div className="mt-5 flex items-center justify-between gap-3 border-t border-[#edf1ed] pt-4"><a href={resource.fileUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#0f4c45] px-4 py-2 text-xs font-bold text-white transition hover:bg-[#0a3b36]">Ouvrir le document <FileText size={14} /></a><button onClick={() => { const reason = window.prompt("Motif du signalement"); if (reason) report.mutate({ resourceId: resource.id, reason }); }} className="inline-flex items-center gap-1 text-xs font-semibold text-[#9a7461] hover:text-[#a94c38]"><ShieldAlert size={14} />Signaler</button></div></article>)}
      {!resources.isLoading && !resources.data?.length && <div className="col-span-full rounded-2xl border border-dashed border-[#c6d9ca] bg-white/70 p-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e0f0e5] text-[#0f4c45]"><Filter size={20} /></div><h2 className="mt-4 font-display text-xl font-bold text-[#0f4c45]">Aucune ressource publiée pour le moment</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#6c8177]">Modifiez vos filtres ou soyez la première personne à enrichir la mémoire académique.</p><Button onClick={() => navigate("/contribuer")} className="mt-5 rounded-full bg-[#0f4c45] text-white hover:bg-[#0a3b36]">Déposer une ressource</Button></div>}
      </div>
    </section>
  </AppShell>;
}

function LibraryIcon() { return <LibraryMark />; }
function LibraryMark() { return <span className="inline-block h-2 w-2 rounded-full bg-[#c87536]" />; }
